@baseUrl = "http://localhost:3000"

###

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "login": "teste",
    "senha": "123",
    "categoria": "admin"
}

